### ISSUE TITLE
when executor_type="funcx" failing  with ValueError: The tasks queue is empty, no tasks were submitted for training!

### ISSUE THREAD

**Issue by vinaBira** [globus-labs/FLoX-prototype#39]
Getting error on quickstart_pytorch.py tutorial with  executor_type="funcx":
Traceback (most recent call last):
  File "flox/examples/quickstart_pytorch/quickstart_pytorch.py", line 130, in <module>
    main()
  File "flox/examples/quickstart_pytorch/quickstart_pytorch.py", line 126, in main
    flox_controller.run_federated_learning()
  File "/home/edg4/FLoX/flox/controllers/MainController.py", line 563, in run_federated_learning
    tasks = self.on_model_broadcast()
  File "/home/edg4/FLoX/flox/controllers/MainController.py", line 371, in on_model_broadcast
    raise ValueError(
ValueError: The tasks queue is empty, no tasks were submitted for training!

**Comment by nikita-kotsehub** [comment]
@vinaBira can you check if your endpoints are active? Your log console should print out the status of each endpoint. If all of them are offline, then no tasks were submitted for training, and therefore the loop terminated with the ValueError.

**Comment by vinaBira** [comment]
@nikita-kotsehub I am using edge devices and yes they are active....Is there any particular state of client machines we are looking for?

**Comment by vinaBira** [comment]
@nikita-kotsehub Please refer the screenshots attached and correct if configuration is wrong at any point.
<img width="468" alt="Screen Shot 2023-07-18 at 12 58 18 PM" src="https://github.com/globus-labs/FLoX/assets/122697509/2cd0b845-95c8-4deb-9b2d-cb5801739000">
<img width="514" alt="Screen Shot 2023-07-18 at 12 58 04 PM" src="https://github.com/globus-labs/FLoX/assets/122697509/1bf295c8-29f7-43a4-a723-dfd34bb521a8">

**Comment by nikita-kotsehub** [comment]
@vinaBira try to run simple funcX tasks on those endpoints before trying out flox. You can find tutorials for simple funcX tasks here: [https://funcx.org/](https://funcx.org/).

If you succeed in that, then there is some issue with the tasks not being submitted to the endpoints. I'd suggest you look through lines of code 311 - 373 in [flox/controllers/MainController.py](https://github.com/globus-labs/FLoX/blob/5cf99b3e16965147a3aff659c4194aa18afc7360/flox/controllers/MainController.py#L311) and try inserting logger or print statements to try to identify at which point the failure occurs. 

Also, did you try running the examples under flox/examples? If not, reading instructions for setup might help.
